version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      ARCH: Win32
      CONFIGURATION: Release
      TOOLSET: v140_xp
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
    - GENERATOR: "Visual Studio 15 2017"
      ARCH: x64
      CONFIGURATION: Release
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    - GENERATOR: "Visual Studio 16 2019"
      ARCH: Win32
      CONFIGURATION: Release
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - GENERATOR: "Visual Studio 16 2019"
      ARCH: x64
      CONFIGURATION: Release
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - GENERATOR: "Visual Studio 16 2019"
      ARCH: x64
      CONFIGURATION: Debug
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"

build_script:
  - md build
  - cd build
  - cmake -G "%GENERATOR%" -A %ARCH% -T "%TOOLSET%" -DPK3_QUIET_ZIPDIR=YES ..
  - cmake --build . --config "%CONFIGURATION%" -- -maxcpucount -verbosity:minimal

after_build:
  - set OUTPUT_DIR=%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\
  - 7z a ..\lzdoom.zip "%OUTPUT_DIR%lzdoom.exe" "%OUTPUT_DIR%*.pk3"

artifacts:
  - path: lzdoom.zip

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
